package com.example.demo.kg.apriori;

import java.util.Set;

/** Association rule generated by Apriori. */
public record AprioriRule(
        Set<AprioriItem> antecedent,
        Set<AprioriItem> consequent,
        double support,
        double confidence,
        double lift,
        int supportCount,
        int transactionCount
) {}
