CREATE SCHEMA IF NOT EXISTS APP;
CREATE SCHEMA IF NOT EXISTS CORE;
CREATE SCHEMA IF NOT EXISTS QC;
CREATE SCHEMA IF NOT EXISTS EVAL;
CREATE SCHEMA IF NOT EXISTS ETL;
CREATE SCHEMA IF NOT EXISTS PROD;
CREATE SCHEMA IF NOT EXISTS KG;
